CARGO_HOME := $(HOME)/.cargo

.SUFFIXES:

.PHONY:
install: $(CARGO_HOME)

.PHONY:
deploy:

.PHONY:
update:

.PHONY:
clean:

$(CARGO_HOME):
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
